---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 5
  cleanup: post
  script:
    configMap:
      name: k6-test
      file: test.js
  arguments: --tag testid=k6-output-8-29-2023-02 --out experimental-prometheus-rw
  runner:
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
    envFrom:
     - secretRef:
         name: k6-mimir-secret
